logging.level.org.springframework.web=INFO
logging.level.com.openclassrooms.debugging=ERROR
# Change this port if you can't start the App
server.port=9999
server.tomcat.mbeanregistry.enabled=true
# Disables cache-control
spring.cache.type=NONE
# Enables Spring MBean export for JConsole
spring.jmx.enabled=true
# Actuator Config
management.metrics.web.server.auto-time-requests=true
management.security.enabled=false
management.endpoints.web.exposure.include=*
management.endpoints.jmx.exposure.include=*
